# Web Server Configuration
server.port=8081

# PostgreSQL Configuration
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/newauditdb}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:postgres}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:2000}
spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false

