databases:
  # 1. PostgreSQL Database
  - name: auditcore-db
    plan: free
    region: oregon

services:

  # 2. Java Spring Boot Service
  - type: web
    name: spring-backend
    env: docker
    region: oregon
    plan: free
    rootDir: AuditTrial-main/backend/springboot/auditSpringBoot
    envVars:
      - key: SPRING_DATASOURCE_URL
        fromDatabase:
          name: auditcore-db
          property: connectionString
      - key: SPRING_DATASOURCE_USERNAME
        fromDatabase:
          name: auditcore-db
          property: user
      - key: SPRING_DATASOURCE_PASSWORD
        fromDatabase:
          name: auditcore-db
          property: password

  # 3. Node.js Log Service
  - type: web
    name: node-logger
    env: node
    region: oregon
    plan: free
    rootDir: AuditTrial-main/backend/nodejs
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: MONGO_ATLAS_URI
        sync: false # You must paste your Mongo URL in the Render Dashboard manually for security!
      - key: MONGO_DB_NAME
        value: gateway_db
      - key: PORT
        value: 3001

  # 4. Python API Gateway
  - type: web
    name: python-gateway
    env: python
    region: oregon
    plan: free
    rootDir: AuditTrial-main/backend/python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: SPRING_URL
        value: https://spring-backend.onrender.com # Auto-links to the Java service
      - key: NODE_URL
        value: https://node-logger.onrender.com # Auto-links to the Node service
      - key: MONGO_ATLAS_URI
        sync: false # You must paste your Mongo URL in the Render Dashboard manually for security!

  # 5. React Frontend
  - type: web
    name: react-dashboard
    env: static
    region: oregon
    plan: free
    rootDir: AuditTrial-main/frontend/frontend
    buildCommand: npm install && npm run build
    publishPath: dist
    envVars:
      - key: VITE_API_BASE_URL
        value: https://python-gateway.onrender.com # Links the frontend to the Python Gateway
